### ISSUE TITLE
Example 02_hpg_gnss_lband_correction - configuration without Wi-Fi

### ISSUE THREAD

**Issue by ftesta-es** [u-blox/XPLR-HPG-software#4]
Hi,

how is it possible to configure the example project without Wi-Fi connection?
Is it possible to embed all the needed information in the code?

Otherwise, would it be possible to require just the Wi-Fi at startup and then disconnecting the WiFi (without powering off the board) for outdoor testing?

Thanks.

**Comment by aangeletos** [comment]
Hello @ftesta-es,

It is not possible to utilize the LBAND examples without a connection to Thingstream since the keys are encrypted and there is no way to hardcode them in the firmware. Please bare in mind that keys have a validity period as well and they need to get updated when they expire. <br>
Currently the examples provided in the repo they require a steady connection to Thingstream's MQTT Point Perfect broker to function as expected. We can add your suggestion to our backlog and we might provide an example behaving the way you describe in a future release but I cannot commit to that.<br>
Our effort and goal is to provide some examples and libraries to get you started with the XPLR-HPG kits.<br>
Examples are not meant to be used as end-applications but rather than a starting point for the users/developers to build their use case. 

Best, 
Alex

**Comment by ftesta-es** [comment]
Hi,

thanks for the feedback and the clarification about this example project.

So, is there no chance to use/load on the D9S and F9R modules the configuration file downloadable from the thingstream portal?
Would they be overwritten on the startup and self-configuration of the NINA?

Thanks

**Comment by dbou-ublox** [comment]
Hi @ftesta-es ,

I tried your proposed setup, which in theory should work

- "Boot with Wi-Fi enabled, in order to get the configuration needed"
- Disconnect Wi-Fi
- See if with L-Band I can keep HPG

I used the vanilla https://github.com/u-blox/XPLR-HPG-software/tree/main/XPLR-HPG-SW/examples/shortrange/05_hpg_wifi_mqtt_correction_captive_portal example to do that (pre-built binaries available in the repo)

I found out that it is **feasible** (Although today, for some reason, I could not get RTK-Fixed easily. Could be related to fires in Athens or so, do not know). See log below:

At 16:52:16, connected to Wi-Fi, RTK-fixed
![image](https://github.com/u-blox/XPLR-HPG-software/assets/74243444/b43430ad-72f4-4b01-ad2b-71a311b32921)

At 16:52:46, I power off the Access Point the DUT is connected to:
![image](https://github.com/u-blox/XPLR-HPG-software/assets/74243444/70dee85f-4007-4899-bdf3-8835e237d771)

At 16:57, I still get RTK-fixed:
![image](https://github.com/u-blox/XPLR-HPG-software/assets/74243444/091ca6b6-e345-4c93-9d0e-e24f048698d4)

Of course, if I power-cycle the DUT (or when the credentials expire), I suspect I would not get correction data any more

Hope this helps a bit,
Dimitris

**Comment by dbou-ublox** [comment]
![image](https://github.com/u-blox/XPLR-HPG-software/assets/74243444/99733607-a4d5-49d5-9891-acfc85a1e241)

P.S. Took me some time to write the previous post it seems :)
