### ISSUE TITLE
GNSS configuration - MultiValSet error code [-1025]

### ISSUE THREAD

**Issue by ftesta-es** [u-blox/XPLR-HPG-software#6]
Hi,

I'm trying to modify the F9R configuration as in the reported list but from the console I get back the MultiValSet error code [-1025].

![image](https://github.com/u-blox/XPLR-HPG-software/assets/138900920/dcb9e770-2895-40b0-80f2-b575c73f3d75)

![image](https://github.com/u-blox/XPLR-HPG-software/assets/138900920/463d072b-b346-4616-a541-345f3995267d)

Which is the reason of this? Why am I not able to apply the same configuration also using the u-center?

Thanks

**Comment by 7Uruz7** [comment]
Hi [ftesta-es](https://github.com/ftesta-es),

It seems you are using the wrong key ID.
When using the set/get values/options command you always have to pick the correct key with the prefix:
```U_GNSS_CFG_VAL_KEY_ID```
and not
```U_GNSS_CFG_VAL_KEY_ITEM```
The latter is meant for the library's internal use.
So in your case the values should be:
```
U_GNSS_CFG_VAL_KEY_ID_SIGNAL_QZSS_ENA_L
U_GNSS_CFG_VAL_KEY_ID_SIGNAL_BDS_ENA_L
```
Please try it and let us know.
Cheers!

**Comment by ftesta-es** [comment]
Hi @7Uruz7 

thanks for the feedback. Indeed, this seems to solve this points.

However I changed the configuration to the following one but I'm still struggling to reach RTK condition:
    {U_GNSS_CFG_VAL_KEY_ID_MSGOUT_UBX_NAV_HPPOSLLH_I2C_U1, 1},
    {U_GNSS_CFG_VAL_KEY_ID_MSGOUT_UBX_NAV_PVT_I2C_U1, 1},
    {U_GNSS_CFG_VAL_KEY_ID_SFCORE_USE_SF_L, 0},
    
    {U_GNSS_CFG_VAL_KEY_ID_RATE_TIMEREF_E1, 0}, 
    {U_GNSS_CFG_VAL_KEY_ID_RATE_MEAS_U2, 100},
    
    {U_GNSS_CFG_VAL_KEY_ID_USBOUTPROT_UBX_L, 1},
    {U_GNSS_CFG_VAL_KEY_ID_USBOUTPROT_NMEA_L, 0},
    {U_GNSS_CFG_VAL_KEY_ID_MSGOUT_UBX_NAV_DOP_USB_U1, 1},
    {U_GNSS_CFG_VAL_KEY_ID_MSGOUT_UBX_NAV_PVT_USB_U1, 1},
    {U_GNSS_CFG_VAL_KEY_ID_MSGOUT_UBX_NAV_STATUS_USB_U1, 1},
    {U_GNSS_CFG_VAL_KEY_ID_MSGOUT_UBX_NAV_HPPOSLLH_USB_U1, 0},
    
    {U_GNSS_CFG_VAL_KEY_ID_SIGNAL_QZSS_ENA_L, 0},
    {U_GNSS_CFG_VAL_KEY_ID_SIGNAL_BDS_ENA_L, 0},
    {U_GNSS_CFG_VAL_KEY_ID_SIGNAL_GAL_ENA_L, 1}

do you suggest to keep also QZSS and BDS? Please keep in mind I'm interested in having a quite high output rate.

Thanks

**Comment by 7Uruz7** [comment]
Hi @ftesta-es,

Nice to hear that the suggested solution worked.

Regarding QZSS and BDS you can find more information on the ZF9 [resources page](https://www.u-blox.com/en/product/zed-f9r-module?legacy=Current#Documentation-&-resources), under interface description found [here](https://www.u-blox.com/sites/default/files/documents/u-blox-F9-HPS-1.30_InterfaceDescription_UBX-22010984.pdf) on pages 244 - 245.
They enable the use of QZSS and Beidu respectively. These options are implementation based and we do not know the exact cases that you might need.
I can also see that you have also opened a ticket [here](https://github.com/u-blox/XPLR-HPG-software/issues/5) regarding RTK issues.
In order to be able to help you better I would suggest to continue this conversation regarding RTK there, since it might contain more information that you have already shared :).
If this is OK by you then we can close this issue.

Cheers,
Dorian

**Comment by ftesta-es** [comment]
Hi @7Uruz7,

All clear, we'll have a look at those resources, thanks.
Ok, I'll close this issue and continue on the other thread.

Best regards,
Filippo
